name: Create Addon Release

on:
  push:
    tags:
      - 'v*'  # Запускается при пуше любых тегов начинающихся с 'v'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: get_version
        run: |
          # Убираем 'v' из тега (v1.2.3 → 1.2.3)
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Building version: $VERSION"

      - name: Create addon directory structure
        run: |
          # Создаем временную папку с правильной структурой для WoW
          mkdir -p AferistHelper
          cp AferistHelper.toc AferistHelper/
          cp AferistHelper.lua AferistHelper/
          cp MuteManager.lua AferistHelper/
          cp AferistHelper_Configs.lua AferistHelper/
          cp README.md AferistHelper/

      - name: Create ZIP archive
        run: |
          # Создаем ZIP архив с именем папки аддона
          zip -r "AferistHelper-${{ steps.get_version.outputs.version }}.zip" AferistHelper/
          echo "📁 Created: AferistHelper-${{ steps.get_version.outputs.version }}.zip"
          
          # Показываем содержимое архива
          echo "📋 Archive contents:"
          unzip -l "AferistHelper-${{ steps.get_version.outputs.version }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: AferistHelper ${{ steps.get_version.outputs.version }}
          body: |
            ## AferistHelper ${{ steps.get_version.outputs.version }}
            
            ### 📦 Automatic Release
            
            **Installation:**
            1. Download the ZIP file
            2. Extract to `World of Warcraft/_classic_/Interface/AddOns/`
            3. Restart the game
            
            ### 📁 Files included:
            - AferistHelper.toc
            - AferistHelper.lua
            - MuteManager.lua
            - AferistHelper_Configs.lua
            
            *Automatically generated release*
          files: |
            AferistHelper-${{ steps.get_version.outputs.version }}.zip
          generate_release_notes: true
