name: Update Addon Version

on:
  push:
    paths:
      - '**.lua'    # Теперь следим за lua файлами в src/
    branches: [ main, master ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[version]')"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Calculate version
        id: version
        run: |
          if [ -f ".base-version" ]; then
            BASE_VERSION=$(cat .base-version)
          else
            BASE_VERSION="1.0"
          fi
          
          BUILD_NUMBER=$(git rev-list --count HEAD)
          NEW_VERSION="${BASE_VERSION}.${BUILD_NUMBER}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update TOC version
        run: |
          # Обновляем TOC файл в папке src/
          sed -i "s/^## Version:.*$/## Version: ${{ steps.version.outputs.new_version }}/" AferistHelper.toc

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/AferistHelper.toc
          git commit -m "chore: auto-build ${{ steps.version.outputs.new_version }} [version]"
          git push
